[package]
name = "mqtt_vault"
version = "0.7.1"
authors = ["Bruce Patterson"]
edition = "2021"
description = "JSON database controlled via MQTT"
documentation = "https://bpatterson.dev/man/mqtt_vault.html"
homepage = "https://bpatterson.dev/projects/mqtt_vault"
repository = "https://github.com/bpatterson-gh/MqttVault"
license = "MPL-2.0"
keywords = ["mqtt", "database", "iot"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.4"
ctrlc = {version = "3.2.2", features = ["termination"] }
json = "0.12.4"
paho-mqtt = "0.11.1"
uuid = { version = "1.0.0", features = ["v4"] }
